// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source interface.go -destination=mock_interface.go -package=task
//

// Package task is a generated GoMock package.
package task

import (
	models "ThreeLayeredArchitecture/models/task"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTaskservice is a mock of Taskservice interface.
type MockTaskservice struct {
	ctrl     *gomock.Controller
	recorder *MockTaskserviceMockRecorder
	isgomock struct{}
}

// MockTaskserviceMockRecorder is the mock recorder for MockTaskservice.
type MockTaskserviceMockRecorder struct {
	mock *MockTaskservice
}

// NewMockTaskservice creates a new mock instance.
func NewMockTaskservice(ctrl *gomock.Controller) *MockTaskservice {
	mock := &MockTaskservice{ctrl: ctrl}
	mock.recorder = &MockTaskserviceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskservice) EXPECT() *MockTaskserviceMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockTaskservice) Add(desc string) (models.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", desc)
	ret0, _ := ret[0].(models.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockTaskserviceMockRecorder) Add(desc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockTaskservice)(nil).Add), desc)
}

// Delete mocks base method.
func (m *MockTaskservice) Delete(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTaskserviceMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTaskservice)(nil).Delete), id)
}

// GetByID mocks base method.
func (m *MockTaskservice) GetByID(id int) (models.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(models.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTaskserviceMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTaskservice)(nil).GetByID), id)
}

// GetPending mocks base method.
func (m *MockTaskservice) GetPending() ([]models.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPending")
	ret0, _ := ret[0].([]models.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPending indicates an expected call of GetPending.
func (mr *MockTaskserviceMockRecorder) GetPending() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPending", reflect.TypeOf((*MockTaskservice)(nil).GetPending))
}

// MarkComplete mocks base method.
func (m *MockTaskservice) MarkComplete(id int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkComplete", id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkComplete indicates an expected call of MarkComplete.
func (mr *MockTaskserviceMockRecorder) MarkComplete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkComplete", reflect.TypeOf((*MockTaskservice)(nil).MarkComplete), id)
}
